--
-- PostgreSQL database dump
--

-- Dumped from database version 12.1
-- Dumped by pg_dump version 12.1

-- Started on 2020-02-13 18:34:45 PST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16394)
-- Name: timer; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA timer;


ALTER SCHEMA timer OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 16395)
-- Name: times; Type: TABLE; Schema: timer; Owner: postgres
--

CREATE TABLE timer.times (
    id smallint NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    net_time time without time zone,
    racer_name text,
    number smallint
);


ALTER TABLE timer.times OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 16401)
-- Name: times_id_seq; Type: SEQUENCE; Schema: timer; Owner: postgres
--

ALTER TABLE timer.times ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME timer.times_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 16398)
-- Name: users; Type: TABLE; Schema: timer; Owner: postgres
--

CREATE TABLE timer.users (
);


ALTER TABLE timer.users OWNER TO postgres;

--
-- TOC entry 3136 (class 0 OID 16395)
-- Dependencies: 203
-- Data for Name: times; Type: TABLE DATA; Schema: timer; Owner: postgres
--

COPY timer.times (id, start_time, end_time, net_time, racer_name, number) FROM stdin;
\.


--
-- TOC entry 3137 (class 0 OID 16398)
-- Dependencies: 204
-- Data for Name: users; Type: TABLE DATA; Schema: timer; Owner: postgres
--

COPY timer.users  FROM stdin;
\.


--
-- TOC entry 3144 (class 0 OID 0)
-- Dependencies: 205
-- Name: times_id_seq; Type: SEQUENCE SET; Schema: timer; Owner: postgres
--

SELECT pg_catalog.setval('timer.times_id_seq', 137, true);


-- Completed on 2020-02-13 18:34:46 PST

--
-- PostgreSQL database dump complete
--

